spring:
  application:
    name: think_different

  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html

  datasource:
    url: jdbc:mysql://localhost:3306/think_different?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root  # MySQL 기본 계정 (sa 대신 root가 일반적)
    password: root  # 비밀번호가 없으면 빈 문자열 설정

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update  # 개발 중엔 update, 운영은 none
    properties:
      hibernate:
        format_sql: true
        show_sql: true  # 개발 중엔 true가 디버깅에 유용

server:
  servlet:
    context-path: /
